### ISSUE TITLE
Brew Cask distribution?

### ISSUE THREAD

**Issue by esttorhe** [keith/conductor#1]
Any chance to have this distributed as a `cask` maybe?

![Giphy](http://media4.giphy.com/media/10XOyCb09KyjLy/giphy.gif)

**Comment by keith** [comment]
Haha. I haven't but I'd be totally happy to if that's something people want! Would you be willing to create the initial config for that for me to maintain with future releases?

**Comment by esttorhe** [comment]
I started transitioning towards `brew` and `cask` just recently; I'm fairly new to it but I can give it a try at least to have the ball rolling :smile:

**Comment by keith** [comment]
Thanks! Otherwise I can try to get to it soon.

**Comment by keith** [comment]
Sorry I still haven't had anytime to get anywhere with this. Have you?

**Comment by keith** [comment]
Just created one. Here's the PR: https://github.com/caskroom/homebrew-cask/pull/12147

**Comment by esttorhe** [comment]
Thank, TBH I completely forgot about this (not that I've had time anyways)

:ok_hand:

**Comment by endocrimes** [comment]
@keith Awesome!

**Comment by keith** [comment]
Looks like I'm going to have to rename this project because of previous conflicts. Suggestions?

**Comment by esttorhe** [comment]
I suck at names; CrabShack ¯\_(ツ)_/¯

TBH I never understood the name `Phoenix`

**Comment by keith** [comment]
Hey guys, changed the name. You'll need to rename `~/.phoenix.js` to `~/.conductor.js` with the new release. The cask PR is pending https://github.com/caskroom/homebrew-cask/pull/12168

**Comment by keith** [comment]
Alright it's in!

```
brew cask install conductor
```

Make sure to move the config file ^

Let me know how it goes!

**Comment by esttorhe** [comment]
:ok_hand:
After uninstalling `Phoenix.js`, installing `Conductor` via `Cask` and renaming the file everything works just as expected :bow: 

Thanks @keith

**Comment by keith** [comment]
Awesome! :+1:
